require('utils/overlay')
require('overlay/framecount')
require('overlay/position')
require('overlay/speed')

local overlayFrameCount = OverlayFrameCount(Overlay(gui, memory))
local overlayPosition = OverlayPosition(Overlay(gui, memory))
local overlaySpeed = OverlaySpeed(Overlay(gui, memory))
mediator:subscribe({ 'frame.displayed' }, function(fc)
    overlayFrameCount:display(fc)
    overlayPosition:display(fc)
    overlaySpeed:display(fc)
end)