local Input = require('utils/input')
require('utils/macro')
require('macro/tricks')

local cf
local input = Input()
local macroTricks = MacroTricks(Macro(input))

-- Puzzle 1
cf = input:cross(2260)
cf = input:down(cf + 60, 9)
cf = input:left(cf, 9)
cf = input:left(cf + 45)
cf = input:down(cf + 1, 19)
cf = input:right(cf + 1)
cf = input:up(cf + 1)
cf = input:cross(cf + 20)

-- Puzzle 2
cf = input:cross(cf + 3)
cf = input:left(cf + 60, 9)
cf = input:down(cf, 9)
cf = input:down(cf + 45)
cf = input:left(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 3
cf = input:cross(cf + 3)
cf = input:left(cf + 60, 9)
cf = input:down(cf, 9)
cf = input:down(cf + 45)
cf = input:left(cf + 1, 19)
cf = input:up(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 4
cf = input:cross(cf + 3)
cf = input:left(cf + 60, 9)
cf = input:up(cf, 9)
cf = input:up(cf + 45)
cf = input:left(cf + 1, 19)
cf = macroTricks:downLeft(cf + 1, 38)
cf = input:down(cf + 1)
cf = input:right(cf + 1)
cf = input:cross(cf + 20)

-- Puzzle 5
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:right(cf + 53)
cf = input:right(cf + 1, 20)
cf = input:cross(cf + 20)

-- Puzzle 6
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:down(cf, 9)
cf = input:down(cf + 47) -- frame lag (waiting 2 frames)
cf = input:right(cf + 1, 19)
cf = macroTricks:upRight(cf + 1, 38)
cf = input:up(cf + 1)
cf = input:left(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 7
cf = input:cross(cf + 3)
cf = input:up(cf + 60, 9) -- frame lag (changing the configuration of the start)
cf = input:up(cf + 53)
cf = input:up(cf + 1, 13)
cf = macroTricks:upLeft(cf + 1) -- /!\ Doing the move on a frame lag make it accessible if the next frame is available
cf = macroTricks:downLeft(cf + 15, 17)
cf = input:left(cf + 1, 2)
cf = input:down(cf + 1, 21)
cf = input:right(cf + 1)
cf = input:cross(cf + 20)

-- Puzzle 8
cf = input:cross(cf + 3)
cf = input:down(cf + 60, 10)
cf = input:right(cf, 9)
cf = input:right(cf + 44)
cf = input:right(cf + 1, 20)
cf = input:down(cf + 1, 10)
cf = input:right(cf + 1, 10)
cf = macroTricks:merryGoOn(cf + 1, 50)
cf = input:right(cf + 1)
cf = input:up(cf + 1, 18)
cf = input:cross(cf + 20)

-- Puzzle 9
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:up(cf, 9)
cf = input:up(cf + 45)
cf = macroTricks:upRight(cf + 1, 19)
cf = input:right(cf, 30)
cf = input:right(cf, 39)
cf = input:up(cf + 1, 2)
cf = input:left(cf + 1, 17)
cf = input:cross(cf + 20)

-- Puzzle 10
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:up(cf, 9)
cf = input:up(cf + 45)
cf = macroTricks:upRight(cf + 1, 19)
cf = input:right(cf, 30)
cf = input:right(cf, 39)
cf = input:up(cf + 1, 2)
cf = input:left(cf + 1, 17)
cf = input:cross(cf + 20)

-- Picture 1
cf = input:cross(cf + 61)

-- Puzzle 11
cf = input:cross(cf + 3)
cf = input:down(cf + 60, 9)
cf = input:left(cf, 9)
cf = input:left(cf + 45)
cf = input:down(cf + 1, 19)
cf = macroTricks:downRight(cf + 1, 20)
cf = input:left(cf + 1)
cf = macroTricks:upLeft(cf + 1, 21)
cf = input:down(cf + 1, 2)
cf = input:cross(cf + 20)

-- Puzzle 12
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:down(cf, 9)
cf = input:down(cf + 45)
cf = input:right(cf + 1, 9)
cf = macroTricks:upRight(cf + 1, 11)
cf = input:right(cf + 1, 9)
cf = macroTricks:downRight(cf + 1, 10)
cf = input:right(cf + 1, 21)
cf = input:down(cf + 1, 19)
cf = input:left(cf + 1, 19)
cf = input:left(cf + 1, 20)
cf = input:cross(cf + 26) -- frame lag (waiting 6 frames)

-- Puzzle 13
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:up(cf, 9)
cf = input:up(cf + 45)
cf = input:up(cf + 1, 20)
cf = input:right(cf + 1, 19)
cf = macroTricks:downRight(cf + 1, 19)
cf = input:down(cf + 1, 20)
cf = input:right(cf + 1)
cf = input:up(cf + 1)
cf = input:cross(cf + 20)

-- Puzzle 14
cf = input:cross(cf + 3)
cf = input:up(cf + 60, 11)
cf = input:left(cf, 9)
cf = input:left(cf + 43)
cf = input:down(cf + 1, 19)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 19)
cf = input:up(cf + 1)
cf = input:left(cf + 1)
cf = input:down(cf + 1, 9)
cf = macroTricks:downRight(cf + 1, 35)
cf = input:right(cf + 1, 2)
cf = input:down(cf + 1, 19)
cf = input:left(cf + 1, 19)
cf = input:left(cf + 1, 20)
cf = input:left(cf + 1, 20)
cf = input:cross(cf + 20)

-- Puzzle 15
cf = input:cross(cf + 3)
cf = input:left(cf + 60, 9)
cf = input:up(cf, 9)
cf = input:up(cf + 45)
cf = input:up(cf + 1, 20)
cf = input:left(cf + 1, 19)
cf = input:left(cf + 1, 20)
cf = input:down(cf + 1, 1)
cf = macroTricks:downRight(cf + 1, 24)
cf = input:down(cf + 1, 14)
cf = input:right(cf + 1)
cf = input:up(cf + 9)
cf = macroTricks:upLeft(cf + 1, 10)
cf = input:left(cf + 1)
cf = input:down(cf + 1)
cf = input:cross(cf + 20)

-- Puzzle 16
cf = input:cross(cf + 3)
cf = macroTricks:downLeft(cf + 60, 14)
cf = input:down(cf + 1, 19)
cf = input:right(cf + 1)
cf = input:up(cf + 1, 64)
cf = macroTricks:upLeft(cf + 1, 12)
cf = macroTricks:upLeft(cf + 11, 5)
cf = input:up(cf + 1, 19)
cf = input:left(cf + 1, 20)
cf = input:down(cf + 1)
cf = input:right(cf + 1, 17)
cf = input:cross(cf + 38)

-- Puzzle 17
cf = input:cross(cf + 3)
cf = input:left(cf + 60, 9)
cf = input:down(cf + 1, 83)
cf = macroTricks:downLeft(cf + 1)
cf = input:down(cf + 1, 37)
cf = input:right(cf + 1, 20)
cf = input:up(cf + 1)
cf = input:left(cf + 1, 13)
cf = macroTricks:downLeft(cf + 1)
cf = input:left(cf + 1, 19)
cf = input:up(cf + 1, 13)
cf = macroTricks:upRight(cf + 1, 2)
cf = input:up(cf + 1, 17)
cf = input:left(cf + 1, 13)
cf = macroTricks:upRight(cf + 1)
cf = input:up(cf + 1, 37)
cf = input:left(cf + 1)
cf = input:down(cf + 1, 13)
cf = input:cross(cf + 20)

-- Puzzle 18
cf = input:cross(cf + 3)
cf = macroTricks:upLeft(cf + 60, 13)
cf = input:left(cf + 1, 20)
cf = input:up(cf + 1, 59)
cf = macroTricks:downRight(cf + 1, 28)
cf = macroTricks:upRight(cf + 1, 53)
cf = input:up(cf + 1, 9)
cf = input:left(cf + 1, 17)
cf = macroTricks:downLeft(cf + 1, 27)
cf = input:up(cf + 1, 14)
cf = input:cross(cf + 20)

-- Puzzle 19
cf = input:cross(cf + 3)
cf = input:up(cf + 60, 9)
cf = input:right(cf, 9)
cf = input:right(cf + 45)
cf = input:up(cf + 1, 19)
cf = input:left(cf + 1)
cf = input:left(cf + 1, 20)
cf = input:down(cf + 1, 19)
cf = input:down(cf + 1, 17)
cf = input:down(cf + 15, 4) -- frame lag (waiting 14 frames + one extra frame for going down)
cf = input:right(cf + 1)
cf = input:up(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 20
cf = input:cross(cf + 3)
cf = input:up(cf + 60, 9)
cf = input:right(cf, 9)
cf = input:right(cf + 45)
cf = input:up(cf + 1, 38)
cf = input:left(cf + 1)
cf = input:down(cf + 1)
cf = input:right(cf + 1, 19)
cf = input:up(cf + 1, 10)
cf = input:left(cf + 15) -- frame lag (waiting 14 frames)
cf = macroTricks:upLeft(cf + 1, 19)
cf = input:left(cf + 1)
cf = input:down(cf + 1)
cf = input:right(cf + 1, 19)
cf = input:up(cf + 1)
cf = input:left(cf + 1)
cf = input:cross(cf + 20)

-- Picture 2
cf = input:cross(cf + 61)

-- Puzzle 21
cf = input:cross(cf + 3)
cf = macroTricks:upRight(cf + 60, 13)
cf = input:up(cf + 1, 79)
cf = macroTricks:downRight(cf + 1, 2)
cf = input:right(cf + 1, 19)
cf = input:up(cf + 1, 18)
cf = macroTricks:upLeft(cf + 1, 28)
cf = input:up(cf + 1, 20)
cf = input:left(cf + 1, 20)
cf = input:down(cf + 1)
cf = input:right(cf + 1, 13)
cf = macroTricks:upRight(cf + 1)
cf = input:right(cf + 1, 28)
cf = macroTricks:downRight(cf + 1, 40)
cf = input:left(cf + 1, 13)
cf = input:cross(cf + 20)

-- Puzzle 22
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = macroTricks:downRight(cf + 41, 14)
cf = input:right(cf + 1, 37)
cf = input:up(cf + 1)
cf = input:left(cf + 1, 13)
cf = macroTricks:downLeft(cf + 1, 28)
cf = input:left(cf + 1, 17)
cf = input:up(cf + 1, 13)
cf = input:cross(cf + 24)

-- Puzzle 23
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:down(cf, 9)
cf = input:down(cf + 45)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 20)
cf = input:right(cf + 1, 20)
cf = input:up(cf + 1, 19)
cf = input:left(cf + 1, 9)
cf = macroTricks:downLeft(cf + 1, 10)
cf = input:down(cf + 1)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 20)
cf = input:right(cf + 1, 20)
cf = input:up(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 24
cf = input:cross(cf + 3)
cf = input:down(cf + 60, 29)
cf = input:right(cf, 9)
cf = input:right(cf + 25)
cf = input:down(cf + 1, 19)
cf = input:down(cf + 1, 20)
cf = input:down(cf + 1, 20)
cf = input:left(cf + 1, 19)
cf = input:up(cf + 1, 48)
cf = macroTricks:upRight(cf + 1)
cf = input:up(cf + 1, 75)
cf = input:left(cf + 1)
cf = input:down(cf + 1, 54)
cf = input:cross(cf + 20)

-- Puzzle 25
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 29)
cf = input:up(cf, 9)
cf = input:up(cf + 25)
cf = input:right(cf + 1, 19)
cf = macroTricks:downRight(cf + 1, 19)
cf = input:down(cf + 1, 20)
cf = input:right(cf + 1, 19)
cf = input:up(cf + 1, 19)
cf = input:left(cf + 1, 19)
cf = input:left(cf + 1, 20)
cf = input:cross(cf + 20)

-- Puzzle 26
cf = input:cross(cf + 3)
cf = input:up(cf + 60, 9)
cf = input:left(cf, 9)
cf = input:left(cf + 45)
cf = input:left(cf + 1, 20)
cf = input:up(cf + 1, 19)
cf = input:up(cf + 1, 20)
cf = input:up(cf + 1, 20)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 20)
cf = input:down(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 27
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:up(cf, 9)
cf = input:up(cf + 45)
cf = macroTricks:upRight(cf + 1, 19)
cf = input:up(cf + 1)
cf = input:left(cf + 1, 9)
cf = macroTricks:downLeft(cf + 1, 37)
cf = input:down(cf + 1)
cf = input:left(cf + 1, 19)
cf = input:left(cf + 1, 20)
cf = input:up(cf + 1, 19)
cf = input:up(cf + 1, 20)
cf = input:cross(cf + 20)

-- Puzzle 28
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 11)
cf = input:up(cf, 9)
cf = input:up(cf + 43)
cf = input:left(cf + 1, 19)
cf = input:down(cf + 1, 9)
cf = macroTricks:downRight(cf + 1, 3)
cf = input:up(cf + 15, 13) -- frame lag
cf = input:left(cf + 1, 9)
cf = macroTricks:downLeft(cf + 1, 10)
cf = input:down(cf + 1)
cf = input:right(cf + 1, 19)
cf = macroTricks:upRight(cf + 1, 18)
cf = input:right(cf + 1, 2)
cf = input:up(cf + 1)
cf = input:cross(cf + 20)

-- Puzzle 29
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:up(cf, 9)
cf = input:up(cf + 45)
cf = input:right(cf + 1, 19)
cf = input:up(cf + 1, 24) -- frame lag (up 5 frames longer)
cf = input:right(cf + 1, 19)
cf = input:up(cf + 1, 19)
cf = input:right(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 30
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 11)
cf = input:up(cf, 9)
cf = input:up(cf + 43)
cf = input:left(cf + 1, 9)
cf = macroTricks:downLeft(cf + 1, 11)
cf = input:left(cf + 1, 18)
cf = input:down(cf + 1, 9)
cf = macroTricks:downRight(cf + 1, 11)
cf = input:down(cf + 1, 18)
cf = input:right(cf + 1, 9)
cf = macroTricks:upRight(cf + 1, 11)
cf = input:right(cf + 1, 18)
cf = input:up(cf + 1, 9)
cf = macroTricks:upLeft(cf + 1, 1)
cf = input:up(cf + 1, 29)
cf = input:left(cf + 1, 3)
cf = input:left(cf + 1, 20)
cf = input:down(cf + 1, 21)
cf = input:right(cf + 1)
cf = input:cross(cf + 20)

-- Picture 3
cf = input:cross(cf + 70) -- frame lag (waiting 9 frames)

-- Puzzle 31
cf = input:cross(cf + 3)
cf = input:up(cf + 60, 9)
cf = input:right(cf, 9)
cf = input:right(cf + 45)
cf = input:right(cf + 1, 20)
cf = input:up(cf + 1, 19)
cf = input:left(cf + 1, 19)
cf = input:left(cf + 1, 20)
cf = input:up(cf + 1, 19)
cf = input:cross(cf + 29) -- frame lag (waiting 9 frames)

-- Puzzle 32
cf = input:cross(cf + 3)
cf = input:left(cf + 60, 11)
cf = input:up(cf, 9)
cf = input:up(cf + 43)
cf = input:right(cf + 1, 19)
cf = input:down(cf + 1, 9)
cf = macroTricks:downLeft(cf + 1, 10)
cf = input:left(cf + 1)
cf = input:down(cf + 1, 18)
cf = macroTricks:downRight(cf + 1, 9)
cf = input:right(cf + 1, 11)
cf = input:up(cf + 1, 12)
cf = macroTricks:upLeft(cf + 1, 9)
cf = input:left(cf + 1, 13)
cf = macroTricks:upRight(cf + 10, 18) -- frame lag
cf = input:up(cf + 1, 2)
cf = input:right(cf + 1, 9)
cf = macroTricks:downRight(cf + 1, 11)
cf = input:down(cf + 1)
cf = input:down(cf + 1, 20)
cf = input:left(cf + 1, 19)
cf = input:up(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 33
cf = input:cross(cf + 3)
cf = input:down(cf + 60, 11)
cf = input:left(cf + 1, 11)
cf = macroTricks:upLeft(cf + 30, 53) -- frame lag
cf = input:left(cf + 1, 28)
cf = macroTricks:downRight(cf + 1, 27)
cf = input:down(cf + 1, 20)
cf = macroTricks:upLeft(cf + 1, 54)
cf = input:up(cf + 1, 27)
cf = macroTricks:downRight(cf + 1, 27)
cf = input:right(cf + 1, 20)
cf = macroTricks:upLeft(cf + 1, 26)
cf = input:left(cf + 1, 21)
cf = macroTricks:upRight(cf + 1, 2)
cf = input:left(cf + 1, 13)
cf = input:cross(cf + 20)

-- Puzzle 34
cf = input:cross(cf + 3)
cf = macroTricks:downLeft(cf + 60, 14)
cf = input:left(cf + 1, 14)
cf = macroTricks:upLeft(cf + 1, 33)
cf = input:up(cf + 1, 20)
cf = input:right(cf + 1, 20)
cf = macroTricks:downLeft(cf + 1, 9) -- frame lag
cf = macroTricks:downRight(cf + 14, 6)
cf = input:down(cf + 1, 19)
cf = input:right(cf + 1, 21)
cf = macroTricks:upRight(cf + 1, 27)
cf = macroTricks:upLeft(cf + 1, 13)
cf = input:left(cf + 1, 18)
cf = macroTricks:upLeft(cf + 1, 13)
cf = input:up(cf + 1, 20)
cf = input:right(cf + 1)
cf = input:down(cf + 1, 43)
cf = input:cross(cf + 20)

-- Puzzle 35
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 11)
cf = input:down(cf + 1, 9)
cf = input:down(cf + 43)
cf = input:left(cf + 1, 19)
cf = input:left(cf + 1, 20)
cf = input:left(cf + 1, 20)
cf = input:up(cf + 1, 19)
cf = input:up(cf + 1, 20)
cf = input:right(cf + 1)
cf = input:down(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 36
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:down(cf + 1, 29)
cf = input:down(cf + 24)
cf = input:right(cf + 1, 19)
cf = input:up(cf + 1, 9)
cf = macroTricks:upLeft(cf + 1, 19)
cf = input:up(cf + 1, 15)
cf = macroTricks:upLeft(cf + 1, 1)
cf = input:up(cf + 1, 14)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 20)
cf = input:down(cf + 1, 19)
cf = input:cross(cf + 28) -- frame lag (waiting 8 frames)

-- Puzzle 37
cf = input:cross(cf + 3)
cf = input:left(cf + 60, 11)
cf = input:up(cf + 1, 9)
cf = input:up(cf + 43)
cf = input:right(cf + 1, 19)
cf = macroTricks:upRight(cf + 1, 20)
cf = input:up(cf + 1, 9)
cf = macroTricks:upLeft(cf + 1, 10)
cf = input:left(cf + 1)
cf = input:down(cf + 1, 19)
cf = macroTricks:downRight(cf + 1, 19)
cf = input:down(cf + 1)
cf = input:left(cf + 1, 19)
cf = macroTricks:upRight(cf + 8, 1) -- frame lag
cf = input:right(cf + 1, 5)
cf = input:cross(cf + 20)

-- Puzzle 38
cf = input:cross(cf + 3)
cf = input:left(cf + 60, 11)
cf = input:up(cf + 1, 9)
cf = input:up(cf + 42)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 20)
cf = input:down(cf + 1, 19)
cf = input:left(cf + 1, 9)
cf = macroTricks:upLeft(cf + 1, 10)
cf = input:up(cf + 1)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 20)
cf = input:down(cf + 1, 19)
cf = input:left(cf + 1, 9)
cf = macroTricks:upLeft(cf + 1, 10)
cf = input:up(cf + 1)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 20)
cf = input:down(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 39
cf = input:cross(cf + 3)
cf = input:left(cf + 60, 11)
cf = input:down(cf + 1, 9)
cf = input:down(cf + 42)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 20)
cf = input:right(cf + 1, 20)
cf = input:up(cf + 1, 19)
cf = input:left(cf + 1, 9)
cf = macroTricks:downLeft(cf + 1, 25)
cf = input:left(cf + 1, 5)
cf = input:down(cf + 1, 1)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 20)
cf = input:up(cf + 1, 19)
cf = input:left(cf + 1, 9)
cf = macroTricks:downLeft(cf + 1, 10)
cf = input:down(cf + 1)
cf = input:right(cf + 1, 19)
cf = input:cross(cf + 26) -- frame lag (waiting 6 frames)

-- Puzzle 40
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:up(cf + 1, 9)
cf = input:up(cf + 44)
cf = input:right(cf + 1, 19)
cf = input:up(cf + 1, 19)
cf = input:left(cf + 1, 19)
cf = input:down(cf + 1, 19)
cf = input:down(cf + 1, 20)
cf = input:cross(cf + 30) -- frame lag (waiting 10 frames)

-- Picture 4
cf = input:cross(cf + 61)

-- Puzzle 41 ; @todo : why the frame lag is not a problem here ?
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:up(cf + 1, 9)
cf = input:up(cf + 44)
cf = input:right(cf + 1, 19)
cf = input:up(cf + 1, 19)
cf = input:left(cf + 1, 19)
cf = input:up(cf + 1, 19)
cf = input:left(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 42
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:down(cf + 1, 9)
cf = input:down(cf + 44)
cf = input:right(cf + 1, 9)
cf = macroTricks:upRight(cf + 1, 10)
cf = input:up(cf + 1, 2)
cf = input:left(cf + 1, 19)
cf = input:down(cf + 1, 9)
cf = macroTricks:downLeft(cf + 1, 9)
cf = macroTricks:downLeft(cf + 16) -- frame lag
cf = input:left(cf + 1, 30)
cf = input:up(cf + 1, 2)
cf = input:up(cf + 1, 20)
cf = input:right(cf + 1, 9)
cf = macroTricks:downRight(cf + 1, 10)
cf = input:down(cf + 1, 21)
cf = input:left(cf + 1)
cf = input:up(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 43
cf = input:cross(cf + 3)
cf = input:left(cf + 60, 9)
cf = input:up(cf + 1, 9)
cf = input:up(cf + 44)
cf = input:left(cf + 1, 19)
cf = input:down(cf + 1, 19)
cf = input:left(cf + 1, 19)
cf = input:left(cf + 1, 20)
cf = input:up(cf + 1, 19)
cf = input:up(cf + 1, 20)
cf = input:cross(cf + 20)

-- Puzzle 44
cf = input:cross(cf + 3)
cf = input:down(cf + 60, 9)
cf = input:right(cf + 1, 9)
cf = input:right(cf + 44)
cf = macroTricks:downRight(cf + 1, 19)
cf = input:right(cf + 1)
cf = input:right(cf + 1, 20)
cf = input:up(cf + 1, 19)
cf = input:left(cf + 1, 9)
cf = macroTricks:upLeft(cf + 1, 19)
cf = input:left(cf + 1, 12)
cf = input:up(cf + 1, 3)
cf = input:right(cf + 1)
cf = input:right(cf + 1, 20)
cf = input:cross(cf + 20)

-- Puzzle 45
cf = input:cross(cf + 3)
cf = macroTricks:upRight(cf + 60, 10)
cf = input:right(cf + 1, 22)
cf = input:up(cf + 1, 41)
cf = input:left(cf + 1, 20)
cf = input:down(cf + 1, 35)
cf = input:up(cf + 1, 55)
cf = input:right(cf + 1, 20)
cf = input:down(cf + 1, 20)
cf = input:left(cf + 1, 17)
cf = input:right(cf + 1, 24)
cf = input:up(cf + 1, 34) -- frame lag
cf = input:left(cf + 1, 3)
cf = input:down(cf + 1, 43)
cf = input:cross(cf + 20)

-- Puzzle 46
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:up(cf + 1, 9)
cf = input:up(cf + 44)
cf = input:right(cf + 1, 19)
cf = input:down(cf + 1, 19)
cf = input:down(cf + 1, 19)
cf = input:left(cf + 1, 9)
cf = macroTricks:upLeft(cf + 1, 10)
cf = input:up(cf + 1)
cf = input:up(cf + 1, 20)
cf = input:right(cf + 1, 19)
cf = input:down(cf + 1)
cf = input:down(cf + 1, 20)
cf = input:left(cf + 1)
cf = input:up(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 47
cf = input:cross(cf + 3)
cf = input:down(cf + 60, 9)
cf = input:left(cf + 1, 9)
cf = input:left(cf + 44)
cf = input:down(cf + 1, 19)
cf = input:right(cf + 1)
cf = input:up(cf + 1, 19)
cf = macroTricks:upRight(cf + 1, 20)
cf = input:right(cf + 1, 19)
cf = input:down(cf + 1, 9)
cf = macroTricks:downLeft(cf + 1, 10)
cf = input:left(cf + 1, 9)
cf = macroTricks:upLeft(cf + 1, 19)
cf = input:up(cf + 1)
cf = input:right(cf + 1, 9)
cf = macroTricks:downRight(cf + 1, 12)
cf = input:right(cf + 1, 17)
cf = input:up(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 48
cf = input:cross(cf + 3)
cf = input:left(cf + 60, 9)
cf = input:up(cf + 1, 9)
cf = input:up(cf + 44)
cf = input:up(cf + 1, 20)
cf = input:left(cf + 1)
cf = input:down(cf + 1, 9)
cf = macroTricks:downRight(cf + 1, 12)
cf = input:down(cf + 1, 17)
cf = input:left(cf + 1, 19)
cf = input:left(cf + 1, 20)
cf = input:up(cf + 1, 19)
cf = input:up(cf + 1, 20)
cf = input:right(cf + 1, 9)
cf = macroTricks:downRight(cf + 1, 15) -- frame lag
cf = input:right(cf + 1, 14)
cf = input:up(cf + 1, 19)
cf = input:right(cf + 1, 19)
cf = input:up(cf + 1, 9)
cf = macroTricks:upLeft(cf + 1, 10)
cf = input:left(cf + 1)
cf = input:down(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 49
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:up(cf + 1, 9)
cf = input:up(cf + 44)
cf = input:right(cf + 1, 19)
cf = input:down(cf + 1, 16) -- frame lag
cf = macroTricks:downLeft(cf + 1, 39)
cf = input:up(cf + 1)
cf = macroTricks:upRight(cf + 1, 21)
cf = input:left(cf + 1, 2)
cf = input:down(cf + 1, 19)
cf = macroTricks:downRight(cf + 1)
cf = input:down(cf + 1, 18)
cf = input:left(cf + 1)
cf = input:up(cf + 1, 9)
cf = macroTricks:upRight(cf + 1, 12)
cf = input:down(cf + 1, 2)
cf = input:down(cf + 1, 20)
cf = input:left(cf + 1, 19)
cf = input:cross(cf + 20)

-- Puzzle 50
cf = input:cross(cf + 3)
cf = input:up(cf + 60, 9)
cf = input:right(cf + 1, 29)
cf = input:right(cf + 24)
cf = input:up(cf + 1, 19)
cf = input:left(cf + 1)
cf = input:left(cf + 1, 20)
cf = input:down(cf + 1, 19)
cf = input:right(cf + 1)
cf = input:up(cf + 1, 19)
cf = input:right(cf + 1, 19)
cf = input:down(cf + 1, 9)
cf = macroTricks:downLeft(cf + 1, 10)
cf = input:down(cf + 1, 19)
cf = input:left(cf + 1, 19)
cf = input:up(cf + 1, 19)
cf = input:up(cf + 1, 20)
cf = input:cross(cf + 20)

-- Picture 5
cf = input:cross(cf + 61)

-- Puzzle 51
cf = input:cross(cf + 3)
cf = input:up(cf + 60, 9)
cf = input:left(cf + 1, 9)
cf = input:left(cf + 44)
cf = input:left(cf + 1, 39)
cf = macroTricks:upDownHesitation(cf + 1, 190)
cf = input:right(cf + 241)
cf = input:up(cf + 1, 19)
cf = input:cross(cf + 24) -- frame lag (waiting 4 frames)

-- Puzzle 52
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:up(cf + 1, 9)
cf = input:up(cf + 44)
cf = input:right(cf + 1, 19)
cf = input:down(cf + 1, 9)
cf = macroTricks:downLeft(cf + 1, 10)
cf = input:down(cf + 1, 19)
cf = input:left(cf + 1)
cf = input:up(cf + 1, 19)
cf = macroTricks:upRight(cf + 1, 19)
cf = input:up(cf + 1)
cf = input:left(cf + 1)
cf = macroTricks:downLeft(cf + 1, 12)
cf = input:up(cf + 16, 5) -- frame lag
cf = input:down(cf + 1)
cf = input:up(cf + 1)
cf = input:cross(cf + 20)

-- Puzzle 53
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:up(cf + 1, 9)
cf = input:up(cf + 44)
cf = macroTricks:upRight(cf + 1, 19)
cf = input:up(cf + 1)
cf = input:left(cf + 1)
cf = input:left(cf + 1, 20)
cf = input:up(cf + 1)
cf = input:down(cf + 1)
cf = macroTricks:danceDanceRevolution(cf + 1, 19)
cf = input:right(cf + 9)
cf = macroTricks:downRight(cf + 1, 20)
cf = input:left(cf + 30)
cf = input:up(cf + 1, 38)
cf = input:down(cf + 1)
cf = input:left(cf + 114, 10)
cf = input:down(cf + 1)
cf = input:down(cf + 106)
cf = input:down(cf + 1, 24)
cf = input:left(cf + 1, 2)
cf = input:right(cf + 15)
cf = input:cross(cf + 20)

-- Puzzle 54
cf = input:cross(cf + 3)
cf = macroTricks:upRight(cf + 60, 10)
cf = input:right(cf + 1, 22)
cf = input:up(cf + 1, 22)
cf = macroTricks:upLeft(cf + 1, 25)
cf = input:up(cf + 1)
cf = input:left(cf + 1, 13)
cf = macroTricks:downRight(cf + 1, 1)
cf = input:left(cf + 1, 13)
cf = macroTricks:downRight(cf + 1, 28)
cf = input:left(cf + 1, 13)
cf = macroTricks:upLeft(cf + 1, 48)
cf = input:up(cf + 1, 3)
cf = input:left(cf + 1, 5)
cf = input:left(cf + 203)
cf = input:up(cf + 1, 20)
cf = input:cross(cf + 20)

-- Puzzle 55
cf = input:cross(cf + 3)
cf = input:left(cf + 60, 48)
cf = input:down(cf + 1, 9)
cf = input:down(cf + 5)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 20)
cf = input:up(cf + 1, 22) -- frame lag
cf = input:left(cf + 1, 16)
cf = input:down(cf + 1)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 19)
cf = input:up(cf + 1, 19)
cf = input:left(cf + 1, 8)
cf = input:down(cf + 1)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 19)
cf = input:up(cf + 1, 19)
cf = input:left(cf + 1, 8)
cf = input:down(cf + 1)
cf = input:right(cf + 1, 19)
cf = macroTricks:upRight(cf + 1, 12)
cf = input:right(cf + 1, 10)
cf = input:down(cf + 1)
cf = input:left(cf + 1, 9)
cf = macroTricks:upLeft(cf + 1, 10)
cf = input:up(cf + 1, 2)
cf = input:right(cf + 1)
cf = input:right(cf + 1, 18)
cf = input:down(cf + 8, 14) -- frame lag
cf = input:cross(cf + 20)

-- Puzzle 56
cf = input:cross(cf + 3)
cf = input:left(cf + 60, 12)
cf = input:up(cf + 1, 3)
cf = input:left(cf + 1)
cf = macroTricks:downLeft(cf + 30, 18)
cf = input:left(cf + 1, 35)
cf = input:up(cf + 1, 20)
cf = input:right(cf + 1, 17)
cf = macroTricks:downLeft(cf + 1, 2)
cf = input:right(cf + 1, 17)
cf = input:up(cf + 1, 21)
cf = macroTricks:upRight(cf + 1, 27)
cf = input:right(cf + 1, 35)
cf = input:down(cf + 1)
cf = input:circle(cf + 1, 40)
cf = input:triangle(cf + 1, 40)
cf = input:circle(cf + 1, 40)
cf = input:right(cf + 1, 12)
cf = input:down(cf + 1)
cf = macroTricks:downRight(cf + 38, 16)
cf = input:down(cf + 1, 17)
cf = input:left(cf + 1, 13)
cf = input:cross(cf + 20)

-- Puzzle 57
cf = input:cross(cf + 3)
cf = input:up(cf + 60, 9)
cf = input:right(cf + 1, 9)
cf = input:right(cf + 44)
cf = input:right(cf + 1, 20)
cf = input:up(cf + 1)
cf = input:up(cf + 1, 20)
cf = input:left(cf + 1)
cf = input:left(cf + 1, 20)
cf = input:left(cf + 1, 20)
cf = input:left(cf + 1, 20)
cf = input:down(cf + 1)
cf = input:select(cf + 1, 217)
cf = macroTricks:rightSelect(cf + 1, 2)
cf = macroTricks:upSelect(cf + 1, 19)
cf = input:select(cf + 1, 19)
cf = input:cross(cf + 1)

-- Puzzle 58
cf = input:cross(cf + 3)
cf = input:right(cf + 60, 9)
cf = input:up(cf + 1, 9)
cf = input:up(cf + 44)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 20)
cf = input:down(cf + 1, 9)
cf = macroTricks:downLeft(cf + 1, 10)
cf = input:left(cf + 1)
cf = input:left(cf + 1, 20)
cf = input:left(cf + 1, 20)
cf = input:up(cf + 1, 19)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 20)
cf = input:down(cf + 1, 48)
cf = input:left(cf + 1, 8)
cf = macroTricks:upLeft(cf + 1, 28)
cf = input:right(cf + 1, 17)
cf = input:cross(cf + 20)

-- Puzzle 59
cf = input:cross(cf + 3)
cf = input:left(cf + 60, 9)
cf = input:down(cf + 1, 9)
cf = input:down(cf + 44)
cf = input:left(cf + 1, 19)
cf = input:up(cf + 1, 9)
cf = macroTricks:upRight(cf + 1, 10)
cf = input:right(cf + 1)
cf = input:down(cf + 1, 9)
cf = macroTricks:downLeft(cf + 1, 29)
cf = input:down(cf + 1)
cf = input:right(cf + 1, 19)
cf = input:right(cf + 1, 20)
cf = input:up(cf + 1, 19)
cf = macroTricks:upLeft(cf + 1, 15)
cf = input:up(cf + 1, 4)
cf = input:left(cf + 17)
cf = input:down(cf + 1, 19)
cf = input:right(cf + 1)
cf = input:up(cf + 1)
cf = input:left(cf + 1, 19)
cf = input:down(cf + 1)
cf = input:right(cf + 1)
cf = input:up(cf + 1, 19)
cf = input:left(cf + 1, 20)
cf = input:cross(cf + 20)

-- Puzzle 60
cf = input:cross(cf + 3)
cf = macroTricks:upRight(cf + 60, 14)
cf = input:up(cf + 1, 54)
cf = input:down(cf + 1, 74)
cf = input:left(cf + 1, 20)
cf = input:up(cf + 1, 20)
cf = input:right(cf + 1, 17)
cf = input:left(cf + 1, 36)
cf = input:down(cf + 1, 20)
cf = input:right(cf + 1)
cf = macroTricks:upRight(cf + 1, 35)
cf = input:cross(cf + 20)

-- Picture 6
cf = input:cross(cf + 61)

return input:all()